version: "3.9"
services:
  sonarqube:
    image: sonarqube:community
    container_name: "sonarqube"
    hostname: "sonarqube"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      # The first default user/password is admin/admin
      SONAR_JDBC_USERNAME: ${SONAR_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_PASSWORD}
    volumes:
      - data:/opt/sonarqube/data
      - extensions:/opt/sonarqube/extensions
      - logs:/opt/sonarqube/logs
    networks:
      - my-network
    ports:
      - "9081:9000"
volumes:
  data:
  extensions:
  logs:
networks:
  my-network:
      name: my-network
      external: true
